/**
 * ICICI Bank Payment Gateway — Payment Advice webhook.
 *
 * ICICI's PG pushes a server-to-server "Payment Advice" POST whenever a
 * transaction's status changes (see "Chapter 8: Payment Advice" in ICICI's
 * Gateway Interface Specification). This is the async webhook: distinct from
 * the browser-redirect "Payment Response" (Chapter 7) that ICICI posts back
 * to `returnURL` when the customer's browser returns from checkout. Both use
 * the same parameter shape and the same secureHash scheme, so this handler
 * covers either if you point the relevant URL at it — but Payment Advice is
 * the one ICICI actually retries on non-200, which is what makes it a real
 * webhook rather than a one-shot redirect callback.
 *
 * IMPORTANT — read before deploying:
 * ICICI's secureHash is NOT a raw-body HMAC. Per "Hash Calculation" in their
 * spec: sort the response's field names alphabetically, concatenate the
 * corresponding values (skipping null/empty ones and secureHash itself) with
 * no separator, then HMAC-SHA256 that string with the merchant's shared key
 * and hex-encode it. This only holds for the default
 * application/x-www-form-urlencoded delivery (Hash Calc V1). If this
 * merchant account was onboarded for JSON-format advices instead, ICICI
 * sends Content-Type: application/json and the hash in a `securehash`
 * request header, computed differently (Hash Calc V2: HMAC over the raw
 * JSON body bytes) — that path is handled separately below. Confirm with
 * ICICI/your onboarding docs which format this merchant is configured for.
 *
 * This function assumes a `paymentOrders/{merchantTxnNo}` document already
 * exists, written when the sale was initiated (the initiateSale API call —
 * not implemented here). Because ICICI's merchantTxnNo can't hold a Firestore
 * path (alphanumeric only, 20 chars max), that lookup document is what maps
 * the transaction back to the tenant/invoice it belongs to — the same
 * pattern this codebase already uses for Razorpay orders
 * (`paymentOrders/{razorpayOrderId}` in functions/lib/index.js). Expected
 * shape:
 *   {
 *     targetCollection: string,  // top-level collection, allowlisted below
 *     targetDocId: string,       // doc within that collection to update
 *   }
 */

import {onRequest, Request} from "firebase-functions/v2/https";
import {defineSecret, defineString} from "firebase-functions/params";
import * as logger from "firebase-functions/logger";
import * as admin from "firebase-admin";
import type {Response} from "express";
import * as crypto from "crypto";

if (!admin.apps.length) {
    admin.initializeApp();
}
const db = admin.firestore();

// The shared key ICICI issues per merchant (same key used to sign
// initiateSale requests) — set with:
//   firebase functions:secrets:set ICICI_PG_SECRET_KEY
const ICICI_SECRET_KEY = defineSecret("ICICI_PG_SECRET_KEY");

// Not secret — ICICI echoes this back in every response; used as a sanity
// check that the advice actually belongs to this merchant account.
const ICICI_MERCHANT_ID = defineString("ICICI_MERCHANT_ID");

// The customer-facing app domain, used only to redirect the *browser* back
// into the app after a Payment Response — never used for the webhook's own
// identity (that's the whitelisted returnURL itself).
const APP_BASE_URL = defineString("APP_BASE_URL");

// Top-level collections a paymentOrders lookup is allowed to point at.
// Defense in depth: the paymentOrders doc is written by our own code, but
// this still stops a corrupted/malicious paymentOrders record from steering
// a write at an arbitrary collection.
const ALLOWED_COLLECTIONS = new Set(["companies", "Invoices", "whatsappActivationRequests"]);

// IST is UTC+5:30. Must stay in sync with istEndOfDay in functions/lib/index.js.
const IST_OFFSET_MS = 5.5 * 60 * 60 * 1000;
function istEndOfDay(baseDate: Date, addDays: number): Date {
    const baseIST = new Date(baseDate.getTime() + IST_OFFSET_MS);
    const y = baseIST.getUTCFullYear();
    const m = baseIST.getUTCMonth();
    const d = baseIST.getUTCDate();
    return new Date(Date.UTC(y, m, d + addDays, 23, 59, 59, 999) - IST_OFFSET_MS);
}

type PaymentStatus = "success" | "failure";

interface ParsedAdvice {
    merchantTxnNo: string;
    txnID: string; // ICICI's unique ref number for this transaction — used for idempotency
    paymentID: string | null; // the authorization/payment id generated by ICICI's auth system
    status: PaymentStatus;
    amount: string | null;
}

/** Hash Calc V1: sort field names, concatenate values, HMAC-SHA256, hex, lowercase. */
function computeSecureHashV1(fields: Record<string, unknown>, secretKey: string): string {
    const concatenated = Object.keys(fields)
        .filter((key) => key !== "secureHash")
        .filter((key) => fields[key] !== null && fields[key] !== undefined && String(fields[key]) !== "")
        .sort()
        .map((key) => String(fields[key]))
        .join("");

    return crypto.createHmac("sha256", secretKey).update(concatenated, "ascii").digest("hex").toLowerCase();
}

function timingSafeEqualHex(a: string, b: string): boolean {
    const bufA = Buffer.from(a, "hex");
    const bufB = Buffer.from(b, "hex");
    if (bufA.length === 0 || bufA.length !== bufB.length) return false;
    return crypto.timingSafeEqual(bufA, bufB);
}

function verifySignature(req: Request, secretKey: string): boolean {
    const contentType = req.headers["content-type"] || "";

    if (contentType.includes("application/json")) {
        // Hash Calc V2: HMAC over the exact raw JSON bytes ICICI sent, hash
        // arrives in the `securehash` header (case-insensitive per spec).
        const headerHash = req.headers["securehash"];
        if (!headerHash || Array.isArray(headerHash)) return false;

        const expected = crypto.createHmac("sha256", secretKey).update(req.rawBody).digest("hex").toLowerCase();
        return timingSafeEqualHex(expected, headerHash.toLowerCase());
    }

    // Hash Calc V1 (default): form-urlencoded body, secureHash is itself one
    // of the posted fields.
    const providedHash = req.body?.secureHash;
    if (!providedHash || typeof providedHash !== "string") return false;

    const expected = computeSecureHashV1(req.body, secretKey);
    return timingSafeEqualHex(expected, providedHash.toLowerCase());
}

function parseAdvice(body: Record<string, unknown>): ParsedAdvice | null {
    const merchantTxnNo = body.merchantTxnNo;
    const txnID = body.txnID;
    if (!merchantTxnNo || !txnID) return null;

    const responseCode = String(body.responseCode ?? "");
    // "000" / "0000" = success. "R1000" = request initiated, not final
    // (mostly out-of-band UPI) — not actionable here, caller should no-op.
    // Anything else = failure.
    if (responseCode === "R1000") return null;

    const status: PaymentStatus = responseCode === "000" || responseCode === "0000" ? "success" : "failure";

    return {
        merchantTxnNo: String(merchantTxnNo),
        txnID: String(txnID),
        paymentID: body.paymentID != null ? String(body.paymentID) : null,
        status,
        amount: body.amount != null ? String(body.amount) : null,
    };
}

interface PaymentOrder {
    targetCollection?: string;
    targetDocId?: string;
    planId?: string;
    planDays?: number;
    couponCode?: string | null;
}

interface ResolvedOrder {
    orderRef: FirebaseFirestore.DocumentReference;
    order: PaymentOrder;
    targetRef: FirebaseFirestore.DocumentReference;
}

async function resolveOrder(merchantTxnNo: string): Promise<ResolvedOrder | null> {
    const orderRef = db.collection("paymentOrders").doc(merchantTxnNo);
    const orderSnap = await orderRef.get();
    if (!orderSnap.exists) return null;

    const order = orderSnap.data() as PaymentOrder;
    if (!order.targetCollection || !order.targetDocId) return null;
    if (!ALLOWED_COLLECTIONS.has(order.targetCollection)) return null;

    return {orderRef, order, targetRef: db.doc(`${order.targetCollection}/${order.targetDocId}`)};
}

export const paymentWebhook = onRequest(
    {secrets: [ICICI_SECRET_KEY], region: "us-central1"},
    async (req: Request, res: Response) => {
        // ICICI's whitelisted returnURL is this same webhook for both the
        // server-to-server Payment Advice (Chapter 8, which expects a plain
        // 200/500 status — never redirect this one, since a redirect isn't a
        // successful-delivery status and would make ICICI retry forever) and
        // the browser-redirect Payment Response (Chapter 7, which should land
        // the customer somewhere friendly). This also covers the customer
        // hitting "back" on ICICI's hosted page, which re-navigates the
        // browser to this same URL, sometimes with a stale/invalid signature.
        // Heuristic: a browser navigation sends an HTML-accepting Accept
        // header; a server-to-server call doesn't.
        const acceptsHtml = String(req.headers["accept"] || "").includes("text/html");
        const configuredBaseUrl = APP_BASE_URL.value();
        const withScheme = configuredBaseUrl && !/^https?:\/\//i.test(configuredBaseUrl) ?
            `https://${configuredBaseUrl}` :
            configuredBaseUrl;
        const appBaseUrl = withScheme ? withScheme.replace(/\/$/, "") : null;

        // Every exit point goes through here: server-to-server calls get the
        // plain status/text ICICI's spec expects, browser navigations get
        // redirected to a friendly status page instead of raw text.
        const finish = (httpStatus: number, text: string, redirectStatusParam: string) => {
            if (acceptsHtml && appBaseUrl) {
                res.redirect(302, `${appBaseUrl}/subscription/payment-return?status=${redirectStatusParam}`);
                return;
            }
            res.status(httpStatus).send(text);
        };

        if (req.method !== "POST") {
            finish(405, "Method Not Allowed", "failure");
            return;
        }

        if (!verifySignature(req, ICICI_SECRET_KEY.value())) {
            logger.warn("paymentWebhook: secureHash verification failed");
            finish(400, "Invalid signature", "failure");
            return;
        }

        const body = req.body as Record<string, unknown>;

        if (ICICI_MERCHANT_ID.value() && String(body.merchantId ?? "") !== ICICI_MERCHANT_ID.value()) {
            logger.warn("paymentWebhook: merchantId mismatch", {received: body.merchantId});
            finish(400, "Unknown merchant", "failure");
            return;
        }

        const advice = parseAdvice(body);
        if (!advice) {
            // Either malformed, or responseCode was R1000 (pending, not
            // actionable) — ack so ICICI doesn't retry a payload we don't
            // need to act on.
            logger.info("paymentWebhook: nothing to process", {body});
            finish(200, "OK", "pending");
            return;
        }

        const resolved = await resolveOrder(advice.merchantTxnNo);
        if (!resolved) {
            logger.error("paymentWebhook: no paymentOrders record for merchantTxnNo", {
                merchantTxnNo: advice.merchantTxnNo,
            });
            finish(400, "Unknown reference", "failure");
            return;
        }
        const {orderRef, order, targetRef} = resolved;

        // Idempotency: one doc per ICICI txnID, created in the same
        // transaction as the target update. A redelivered advice for a
        // txnID we've already processed is a no-op — still ack with 200.
        const idempotencyRef = db.collection("processedWebhookEvents").doc(advice.txnID);

        try {
            await db.runTransaction(async (tx) => {
                const idempotencySnap = await tx.get(idempotencyRef);
                if (idempotencySnap.exists) {
                    logger.info("paymentWebhook: duplicate txnID, skipping", {txnID: advice.txnID});
                    return;
                }

                // Activation (mirrors verifyRazorpayPayment's transaction in
                // functions/lib/index.js) needs the company's current expiry
                // before we can extend it — read before any writes.
                const shouldActivate = advice.status === "success" && order.targetCollection === "companies";
                const targetSnap = shouldActivate ? await tx.get(targetRef) : null;

                tx.set(idempotencyRef, {
                    merchantTxnNo: advice.merchantTxnNo,
                    paymentID: advice.paymentID,
                    status: advice.status,
                    processedAt: admin.firestore.FieldValue.serverTimestamp(),
                });

                tx.set(
                    targetRef,
                    {
                        paymentStatus: advice.status,
                        paymentId: advice.paymentID,
                        icicTxnId: advice.txnID,
                        ...(advice.amount !== null ? {paymentAmount: advice.amount} : {}),
                        paymentUpdatedAt: admin.firestore.FieldValue.serverTimestamp(),
                    },
                    {merge: true}
                );

                tx.set(
                    orderRef,
                    {
                        status: advice.status === "success" ? "paid" : "failed",
                        ...(advice.status === "success" ? {paidAt: admin.firestore.FieldValue.serverTimestamp()} : {}),
                    },
                    {merge: true}
                );

                if (shouldActivate && targetSnap && order.planId) {
                    const companyData = targetSnap.data() || {};
                    const currentExpiry = companyData.expiryDate && companyData.expiryDate.toDate ?
                        companyData.expiryDate.toDate() :
                        new Date();
                    const baseDate = currentExpiry > new Date() ? currentExpiry : new Date();
                    const newExpiryDate = istEndOfDay(baseDate, order.planDays || 365);

                    tx.set(
                        targetRef,
                        {
                            expiryDate: admin.firestore.Timestamp.fromDate(newExpiryDate),
                            pack: order.planId,
                            validity: "active",
                            isTrial: false,
                        },
                        {merge: true}
                    );

                    if (order.couponCode) {
                        const redemptionRef = db.doc(`couponRedemptions/${order.couponCode}_${order.targetDocId}`);
                        const couponRef = db.doc(`coupons/${order.couponCode}`);
                        tx.set(
                            redemptionRef,
                            {
                                code: order.couponCode,
                                companyId: order.targetDocId,
                                orderId: orderRef.id,
                                redeemedAt: admin.firestore.FieldValue.serverTimestamp(),
                            },
                            {merge: true}
                        );
                        tx.set(couponRef, {redemptionCount: admin.firestore.FieldValue.increment(1)}, {merge: true});
                    }
                }

                // Sellar WhatsApp plan top-up — separate product from the
                // subscription above, never touches expiryDate/pack. Field
                // names (status/requestedPlanId) match what WAChooseProvider.tsx
                // and the super-admin WhatsApp page already read.
                if (
                    advice.status === "success" &&
                    order.targetCollection === "whatsappActivationRequests" &&
                    order.planId
                ) {
                    tx.set(
                        targetRef,
                        {
                            status: "paid",
                            requestedPlanId: order.planId,
                            paidAt: admin.firestore.FieldValue.serverTimestamp(),
                        },
                        {merge: true}
                    );
                }
            });

            finish(200, "OK", advice.status);
        } catch (error) {
            logger.error("paymentWebhook: failed to process advice", {error, txnID: advice.txnID});
            // 500 so ICICI's advice retry mechanism gets a chance to redeliver
            // (only matters for the server-to-server path — finish() never
            // redirects a real advice call to a 200-only browser page).
            finish(500, "Internal Error", "failure");
        }
    }
);
