export const ROUTES = {
  HOME: '/',
  JOURNAL: '/journal',
  MASTERS: '/masters',
  REPORTS: '/reports',
  ACCOUNT: '/account',
  SALES: '/sales',
  SALES_RETURN: '/sales-return',
  PURCHASE: '/purchase',
  PURCHASE_RETURN: '/purchase-return',
  ITEM_ADD: '/item-add',
  ITEM_GROUP: '/item-group',
  USER_ADD: '/user-add',
  SHOP_SETUP2: '/shop--setup',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  EDIT_PROFILE: '/edit-profile',
  LANDING: '/landing',
  ITEM_REPORT: '/item-report',
  RESTOCK_REPORT: '/restock-report',
  TAX_REPORT: '/tax-report',
  CUSTOMER_REPORT: '/customer-report',
  SALES_REPORT: '/sales-report',
  PURCHASE_REPORT: '/purchase-report',
  PNL_REPORT: '/pnl-report',
  BUSINESS_INFO: '/bus-info',
  SHOP_SETUP: '/shop-setup',
  PRINTQR: '/printqr',
  PERMSETTING: '/permsetting',
  UNAUTHORIZED: '/unauthorized',
  SALESETTING: '/sales-setting',
  PURCHASESETTING: '/purchase-setting',
  HISTORY: '/history',
  USERSETTING: '/user-setting',
  BILLSETTING: '/bill-setting',
  ITEMSETTING: '/item-setting',
  CHOME: '/catalogue-home',
  MYSHOP: 'my-shop',
  ORDER: 'orders',
  ORDERDETAILS: 'order-details',
  CATALOGUE: 'catalogue',
  CATALOGUE_ACCOUNTS: 'accounts',
  CATALOGUE_REPORTS: 'reports',
  CATALOGUE_SALES: 'sales',
  CATALOGUE_PNL_REPORT:'profit-loss',
  CATALOGUE_ITEM_REPORT:'item',
  CATALOGUE_CUSTOMER_REPORT:'customer-report',
  CATALOGUE_USER_REPORT:'user-report',
  CATALOGUE_TAX_REPORT:'tax-report',
  SUBSCRIPTION_PAGE: '/subscription',
  SUPPORT_PAGE: '/support',
  ADD_PRODUCT: 'add-product',
  CAT_ITEM_GROUP: 'item-groups',
  MANAGE_ITEMS: '/manage-items',
  ORDER_RETURN:'order-return',
  CATA_MASTERS:'cata-masters',
  CATA_SALE_SETTING:'cata-sales-setting',
  CATA_BILL_SETTING:'cata-bill-setting',
  CATA_ITEM_SETTING:'cata-item-setting',
  CATA_USER_SETTING:'cata-user-setting',
  CATA_PERMISSION_SETTING:'cata-permission-setting',
  CATA_EDIT:'cata-edit-profile',
  CATA_REQUEST:'requests',
};
