export const ROUTES = {
  HOME: '/',
  JOURNAL: '/journal',
  MASTERS: '/masters',
  REPORTS: '/reports',
  ACCOUNT: '/account',
  SALES: '/sales',
  SALES_RETURN: '/sales-return',
  PURCHASE: '/purchase',
  PURCHASE_RETURN: '/purchase-return',
  ITEM_ADD: '/item-add',
  ITEM_GROUP: '/item-group',
  USER_ADD: '/user-add',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  EDIT_PROFILE: '/edit-profile',
  LANDING: '/landing',
  ITEM_REPORT: '/item-report',
  SALES_REPORT: '/sales-report',
  PURCHASE_REPORT: '/purchase-report',
  PNL_REPORT: '/pnl-report',
  BUSINESS_INFO: '/bus-info',
  BUSINESS_ADDRESS: '/bus-address',
  PRINTQR: '/printqr',
  PERMSETTING: '/permsetting',
  UNAUTHORIZED: '/unauthorized',
  SALESETTING: '/sales-setting',
  PURCHASESETTING: '/purchase-setting',
  HISTORY: '/history',
  USERSETTING: '/user-setting',
  ITEMSETTING: '/item-setting',
  // Catalog / public storefront routes
  CATALOGUE_HOME: '/catalogue',
  MY_SHOP: '/catalogue/my-shop',
  ORDERS: '/catalogue/orders',
  ORDER_DETAILS: '/catalogue/order-details',
  CATALOGUE_ACCOUNT: '/catalogue/account',
  CATALOGUE: '/catalogue/:companyId',
  // (POS) settings and misc - keep original keys for POS routes
};
