// pnlReport.downloads.ts
//
// PDF / Excel export engine for the Profit & Loss report. Extracted verbatim
// (same calculations/formatting) from PNLReport.tsx so the page component
// only has to wire up state + trigger these, mirroring the sibling
// `TaxReportComponents/taxReportExport.utils.ts` pattern.

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import XLSX from 'xlsx-js-style';

import { formatDate } from './pnlReport.utils';
import { resolveCompanyLogoBase64 } from '../../../Catalogue/hooks/useCompanyLogo';
import type { TransactionDetail } from './pnlReport.utils';

/** Minimal local typing for the xlsx-js-style cell style shape (no upstream types shipped). */
interface XlsxFont { name?: string; sz?: number; bold?: boolean; italic?: boolean; color?: { rgb: string } }
interface XlsxFill { patternType: string; fgColor: { rgb: string } }
interface XlsxAlignment { horizontal?: string; vertical?: string; wrapText?: boolean }
interface XlsxBorderSide { style: string; color: { rgb: string } }
interface XlsxBorder {
  top?: XlsxBorderSide;
  bottom?: XlsxBorderSide;
  left?: XlsxBorderSide;
  right?: XlsxBorderSide;
}
interface XlsxCellStyle {
  font: XlsxFont;
  fill: XlsxFill | Record<string, never>;
  alignment: XlsxAlignment;
  border: XlsxBorder | Record<string, never>;
}
type XlsxCellValue = string | number | null;

export interface PnlSummary {
  totalRevenue: number;
  totalCost: number;
  totalExpenses: number;
  grossProfit: number;
  grossProfitPercentage: number;
}

export interface PnlExportParams {
  pnlSummary: PnlSummary;
  filteredTransactions: TransactionDetail[];
  appliedFilters: { start: string; end: string } | null;
  startDate: string;
  endDate: string;
  companyId: string | undefined;
}

const inr = (value: number) =>
  value.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

/** Generates and downloads the P&L report as a branded PDF. */
export async function downloadPnlPdf({
  pnlSummary,
  filteredTransactions,
  appliedFilters,
  startDate,
  endDate,
  companyId,
}: PnlExportParams): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const { totalRevenue, totalCost, grossProfit, grossProfitPercentage } = pnlSummary;
  // ===== GENERATION TAG (drawn first, reserves space for logo) =====
  const tagText = `Generated by SELLAR • ${new Date().toLocaleString('en-IN')}`;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);

  const textWidth = doc.getTextWidth(tagText);
  const paddingX = 2;
  const boxWidth = textWidth + paddingX * 2;
  const boxHeight = 5;

  const logoReservedWidth = 25; // space reserved for logo + gap, so tag never overlaps it
  const boxX = pageWidth - 14 - logoReservedWidth - boxWidth;
  const boxY = 10;

  doc.setFillColor(245, 245, 245);
  doc.rect(boxX, boxY, boxWidth, boxHeight, 'F');

  doc.setTextColor(80, 80, 80);
  doc.text(tagText, boxX + paddingX, boxY + 3.5);

  doc.setTextColor(0, 0, 0);

  // ===== LOGO (drawn after, in its own reserved slot at top-right corner) =====
  try {
    const base64Logo = await resolveCompanyLogoBase64(companyId);
    if (base64Logo) {
      const img = new Image();
      img.src = base64Logo;
      await new Promise<void>((resolve) => {
        img.onload = () => {
          const logoWidth = 15;
          const logoHeight = (img.naturalHeight / img.naturalWidth) * logoWidth;
          const logoX = pageWidth - logoWidth - 14;
          doc.addImage(base64Logo, 'PNG', logoX, 8, logoWidth, logoHeight);
          resolve();
        };
        img.onerror = () => resolve();
      });
    }
  } catch {
    // Continue without logo
  }

  // --- 1. BRAND ACCENT BAR ---
  doc.setFillColor(37, 99, 235); // blue-600
  doc.rect(0, 0, pageWidth, 6, 'F');

  // --- 2. HEADER SECTION ---
  doc.setFontSize(22);
  doc.setTextColor(17, 24, 39); // gray-900
  doc.setFont('helvetica', 'bold');
  doc.text('Profit & Loss Report', 14, 24);

  // Dynamic Subtitle with Date Range
  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128); // gray-500
  doc.setFont('helvetica', 'normal');

  const generationDate = new Date().toLocaleDateString('en-IN', {
    year: 'numeric', month: 'short', day: 'numeric',
  });

  const start = appliedFilters?.start ? formatDate(new Date(appliedFilters.start)) : 'All Time';
  const end = appliedFilters?.end ? formatDate(new Date(appliedFilters.end)) : 'All Time';

  const subtitleText = `Generated: ${generationDate}   |   Period: ${start} to ${end}`;
  doc.text(subtitleText, 14, 31);

  // --- 3. SUMMARY METRICS BLOCK ---
  autoTable(doc, {
    startY: 38,
    body: [
      [
        'TOTAL SALES (Rs.)',
        inr(totalRevenue),
        'GROSS PROFIT / LOSS (Rs.)',
        inr(grossProfit),
      ],
      [
        'TOTAL COST (Rs.)',
        inr(totalCost),
        'GROSS MARGIN',
        `${grossProfitPercentage.toFixed(2)}%`,
      ],
      [
        'TOTAL EXPENSES (Rs.)',
        inr(pnlSummary.totalExpenses ?? 0),
        '',
        '',
      ],
    ],
    theme: 'plain',
    styles: {
      font: 'helvetica',
      cellPadding: 4,
      fontSize: 11,
      textColor: [17, 24, 39], // gray-900
    },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [107, 114, 128], cellWidth: 40 }, // Labels
      1: { fontStyle: 'bold', halign: 'right', cellWidth: 40 },            // Values
      2: { fontStyle: 'bold', textColor: [107, 114, 128], cellWidth: 55 }, // Labels
      3: { fontStyle: 'bold', halign: 'right', cellWidth: 40 },            // Values
    },
    didParseCell: function (data) {
      // Highlight negative Gross Profit or Margin in red
      if ((data.row.index === 0 && data.column.index === 3) ||
        (data.row.index === 1 && data.column.index === 3)) {
        const rawVal = parseFloat(String(data.cell.raw).replace(/,/g, '').replace('%', ''));
        if (rawVal < 0) {
          data.cell.styles.textColor = [220, 38, 38]; // red-600
        }
      }
    },
  });

  // --- 4. DETAILED TRANSACTIONS TABLE ---
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 12,
    head: [['DATE', 'INVOICE', 'SALES (Rs.)', 'COST (Rs.)', 'PROFIT (Rs.)']],
    body: filteredTransactions.map((t) => [
      formatDate(t.createdAt),
      t.invoiceNumber || 'N/A',
      inr(t.totalAmount),
      inr(t.costOfGoodsSold || 0),
      inr(t.profit || 0),
    ]),
    foot: [[
      'TOTAL',
      '-',
      inr(totalRevenue),
      inr(totalCost),
      inr(grossProfit),
    ]],
    theme: 'plain',
    styles: {
      font: 'helvetica',
      cellPadding: 7,
      fontSize: 10,
      textColor: [55, 65, 81], // gray-700
    },
    headStyles: {
      fillColor: [249, 250, 251], // gray-50
      textColor: [17, 24, 39], // gray-900
      fontStyle: 'bold',
      halign: 'center',
      lineWidth: { top: 1, bottom: 1 },
      lineColor: [229, 231, 235], // gray-200
    },
    footStyles: {
      fillColor: [255, 255, 255],
      textColor: [17, 24, 39],
      fontStyle: 'bold',
      halign: 'right', // Right aligns the totals to match the data columns
      lineWidth: { top: 1, bottom: 2 }, // Thicker bottom line for totals
      lineColor: [17, 24, 39],
    },
    alternateRowStyles: {
      fillColor: [252, 252, 252], // Subtle zebra striping
    },
    columnStyles: {
      0: { halign: 'left', cellWidth: 35 },
      1: { halign: 'left', cellWidth: 'auto' },
      2: { halign: 'right', cellWidth: 35 },
      3: { halign: 'right', cellWidth: 35 },
      4: { halign: 'right', cellWidth: 35 },
    },
    // --- 5. CONDITIONAL FORMATTING ---
    didParseCell: function (data) {
      // Highlight negative values in the 'Profit' column for body and foot
      if ((data.section === 'body' || data.section === 'foot') && data.column.index === 4) {
        const rawVal = parseFloat(String(data.cell.raw).replace(/,/g, ''));
        if (rawVal < 0) {
          data.cell.styles.textColor = [220, 38, 38]; // red-600
          data.cell.styles.fontStyle = 'bold';
        }
      }
      // Fix alignment for the "TOTAL" label in the footer
      if (data.section === 'foot' && data.column.index === 0) {
        data.cell.styles.halign = 'left';
      }
    },
    // --- 6. PAGINATION FOOTER ---
    didDrawPage: function () {
      const pageCount = (doc.internal as any).getNumberOfPages();
      doc.setFontSize(9);
      doc.setTextColor(156, 163, 175); // gray-400
      doc.text(
        `Page ${pageCount}`,
        pageWidth - 14,
        pageHeight - 10,
        { align: 'right' },
      );
    },
  });

  // Safely naming the file based on the parsed dates
  const safeStart = appliedFilters?.start ? startDate : 'All_Time';
  const safeEnd = appliedFilters?.end ? endDate : 'All_Time';
  doc.save(`PNL_Report_${safeStart}_to_${safeEnd}.pdf`);
}

/** Generates and downloads the P&L report as a styled Excel workbook. */
export function downloadPnlExcel({
  pnlSummary,
  filteredTransactions,
  appliedFilters,
  startDate,
  endDate,
}: PnlExportParams): void {
  const s = (font: XlsxFont, fill?: XlsxFill, alignment?: XlsxAlignment, border?: XlsxBorder): XlsxCellStyle => ({
    font: { name: 'Arial', ...font },
    fill: fill ?? {},
    alignment: alignment ?? { horizontal: 'center', vertical: 'center', wrapText: true },
    border: border ?? {},
  });
  const solidFill = (rgb: string) => ({ patternType: 'solid', fgColor: { rgb } });
  const allBorders = {
    top: { style: 'thin', color: { rgb: 'CBD5E1' } },
    bottom: { style: 'thin', color: { rgb: 'CBD5E1' } },
    left: { style: 'thin', color: { rgb: 'CBD5E1' } },
    right: { style: 'thin', color: { rgb: 'CBD5E1' } },
  };
  const bblr = {
    bottom: { style: 'thin', color: { rgb: 'CBD5E1' } },
    left: { style: 'thin', color: { rgb: 'CBD5E1' } },
    right: { style: 'thin', color: { rgb: 'CBD5E1' } },
  };

  const generationDate = new Date().toLocaleDateString('en-IN', {
    year: 'numeric', month: 'short', day: 'numeric',
  });

  const periodLabel = appliedFilters
    ? `Period: ${formatDate(new Date(appliedFilters.start))} – ${formatDate(new Date(appliedFilters.end))}`
    : 'Period: All';

  // ── COLUMN DEFINITIONS ──────────────────────────────────────────────
  const COLS = [
    { header: '#', width: 6 },
    { header: 'Date', width: 18 },
    { header: 'Invoice', width: 22 },
    { header: 'Sales (₹)', width: 22 },
    { header: 'Cost (₹)', width: 22 },
    { header: 'Profit (₹)', width: 22 },
  ];
  const colCount = COLS.length;

  // Row layout:
  // 0  → Title (merged)
  // 1  → Meta (merged)
  // 2  → blank spacer
  // 3  → Summary label (merged)
  // 4  → Summary values
  // 5  → blank spacer
  // 6  → Column headers
  // 7+ → Data rows
  // Last → Totals footer

  const dataStartRow = 7;
  const totalRows = dataStartRow + filteredTransactions.length + 1;
  const aoa: XlsxCellValue[][] = Array.from({ length: totalRows }, () => Array(colCount).fill(null));

  // Row 0 – Title
  aoa[0][0] = 'Profit & Loss Report';

  // Row 1 – Meta
  aoa[1][0] = `Generated: ${generationDate}   |   ${periodLabel}   |   Transactions: ${filteredTransactions.length}`;

  // Row 3 – Summary label
  aoa[3][0] = 'SUMMARY';

  // Row 4 – Summary values (single merged cell)
  aoa[4][0] = `Total Sales: ₹${inr(pnlSummary.totalRevenue)}   |   Total Cost: ₹${inr(pnlSummary.totalCost)}   |   Expenses: ₹${inr(pnlSummary.totalExpenses ?? 0)}   |   Net Profit: ₹${inr(pnlSummary.grossProfit)}   |   Net Margin: ${pnlSummary.grossProfitPercentage.toFixed(2)}%`;

  // Row 6 – Column headers
  COLS.forEach((c, i) => { aoa[6][i] = c.header; });

  // Rows 7+ – Data
  filteredTransactions.forEach((txn, idx) => {
    const r = dataStartRow + idx;
    aoa[r][0] = idx + 1;
    aoa[r][1] = formatDate(txn.createdAt);
    aoa[r][2] = txn.invoiceNumber || 'N/A';
    aoa[r][3] = Math.round(txn.totalAmount);
    aoa[r][4] = Math.round(txn.costOfGoodsSold || 0);
    aoa[r][5] = Math.round(txn.profit || 0);
  });

  // Footer row
  const footerRow = dataStartRow + filteredTransactions.length;
  aoa[footerRow][0] = 'TOTAL';
  aoa[footerRow][1] = `${filteredTransactions.length} transactions`;
  aoa[footerRow][3] = Math.round(pnlSummary.totalRevenue);
  aoa[footerRow][4] = Math.round(pnlSummary.totalCost);
  aoa[footerRow][5] = Math.round(pnlSummary.grossProfit);

  // ── BUILD WORKSHEET ──────────────────────────────────────────────────
  const worksheet = XLSX.utils.aoa_to_sheet(aoa);
  worksheet['!cols'] = COLS.map(c => ({ wch: c.width }));
  worksheet['!rows'] = [
    { hpt: 36 }, // 0 title
    { hpt: 20 }, // 1 meta
    { hpt: 8 },  // 2 spacer
    { hpt: 18 }, // 3 summary label
    { hpt: 48 }, // 4 summary values
    { hpt: 8 },  // 5 spacer
    { hpt: 28 }, // 6 headers
    ...filteredTransactions.map(() => ({ hpt: 20 })),
    { hpt: 24 }, // footer
  ];

  worksheet['!merges'] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: colCount - 1 } },
    { s: { r: 1, c: 0 }, e: { r: 1, c: colCount - 1 } },
    { s: { r: 3, c: 0 }, e: { r: 3, c: colCount - 1 } },
    { s: { r: 4, c: 0 }, e: { r: 4, c: colCount - 1 } },
    { s: { r: footerRow, c: 1 }, e: { r: footerRow, c: 2 } },
  ];

  const style = (addr: string, st: XlsxCellStyle) => {
    if (!worksheet[addr]) worksheet[addr] = { t: 's', v: '' };
    worksheet[addr].s = st;
  };

  // ── APPLY STYLES ─────────────────────────────────────────────────────

  // Title (row 0)
  style('A1', s(
    { sz: 16, bold: true, color: { rgb: 'FFFFFF' } },
    solidFill('2563EB'),
    { horizontal: 'center', vertical: 'center' },
  ));

  // Meta (row 1)
  style('A2', s(
    { sz: 9, italic: true, color: { rgb: '475569' } },
    solidFill('DBEAFE'),
    { horizontal: 'center', vertical: 'center' },
  ));

  // Summary label (row 3)
  style('A4', s(
    { sz: 10, bold: true, color: { rgb: '1D4ED8' } },
    solidFill('EFF6FF'),
    { horizontal: 'left', vertical: 'center' },
    allBorders,
  ));

  style('A5', s(
    { sz: 10, bold: true, color: { rgb: '166534' } },
    solidFill('DCFCE7'),
    { horizontal: 'center', vertical: 'center', wrapText: true },
    bblr,
  ));

  // Column headers (row 6)
  COLS.forEach((_c, i) => {
    const addr = XLSX.utils.encode_cell({ r: 6, c: i });
    style(addr, s(
      { sz: 10, bold: true, color: { rgb: 'FFFFFF' } },
      solidFill('1E40AF'),
      { horizontal: i <= 2 ? 'left' : 'center', vertical: 'center' },
      allBorders,
    ));
  });

  // Numeric column indices: 3 = Sales, 4 = Cost, 5 = Profit
  const numericCols = new Set([3, 4, 5]);

  // Data rows
  filteredTransactions.forEach((_txn, idx) => {
    const r = dataStartRow + idx;
    const isAlt = idx % 2 === 1;
    const rowBg = solidFill(isAlt ? 'F8FAFC' : 'FFFFFF');

    for (let ci = 0; ci < colCount; ci++) {
      const addr = XLSX.utils.encode_cell({ r, c: ci });
      const isNumeric = numericCols.has(ci);
      style(addr, s(
        { sz: 9, color: { rgb: '1E293B' } },
        rowBg,
        { horizontal: isNumeric ? 'center' : 'left', vertical: 'center' },
        bblr,
      ));
      if (worksheet[addr] && isNumeric) {
        worksheet[addr].t = 'n';
        worksheet[addr].z = '₹#,##0.00';
      }
    }
  });

  // Footer row
  for (let ci = 0; ci < colCount; ci++) {
    const addr = XLSX.utils.encode_cell({ r: footerRow, c: ci });
    style(addr, s(
      { sz: 10, bold: true, color: { rgb: '1E293B' } },
      solidFill('E2E8F0'),
      { horizontal: ci <= 2 ? 'left' : 'center', vertical: 'center' },
      {
        top: { style: 'medium', color: { rgb: '1E293B' } },
        bottom: { style: 'medium', color: { rgb: '1E293B' } },
        left: { style: 'thin', color: { rgb: 'CBD5E1' } },
        right: { style: 'thin', color: { rgb: 'CBD5E1' } },
      },
    ));
    if ([3, 4, 5].includes(ci) && worksheet[addr]) {
      worksheet[addr].t = 'n';
      worksheet[addr].z = '₹#,##0.00';
    }
  }

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'PNL Report');
  XLSX.writeFile(workbook, `PNL-Report-${startDate}-to-${endDate}.xlsx`);
}
