export enum Cata_Permissions {

    ViewCatalogueDashboard = 'ViewCatalogueDashboard',
    ViewCatalogueAccounts = 'ViewCatalogueAccounts',
    ViewCatalogueOrders = 'ViewCatalogueOrders',
    ViewCatalogueRequests = 'ViewCatalogueRequests',
    ManageItems = 'ManageItems',
    ViewReports = 'ViewReports',
    ViewItemReport = 'ViewItemReport',
    ViewPartyLedger = 'ViewPartyLedger',
    ViewItemSoldReport = 'ViewItemSoldReport',
    ViewSalesReport = 'ViewSalesReport',
    ViewPNLReport = 'ViewPNLReport',
    ViewCustomerReport = 'ViewCustomerReport',
    ViewUserReport = 'ViewUserReport',
    ViewTaxReport = 'ViewTaxReport',
    ManageEditProfile = 'ManageEditProfile',
    ManageMasters = 'ManageMasters',
    ManageSalesSettings = 'ManageSalesSettings',
    ManageBillSettings = 'ManageBillSettings',
    ManageItemSettings = 'ManageItemSettings',
    ManageUserSettings = 'ManageUserSettings',
    ManagePermissions = 'ManagePermissions',
    ViewShop = 'ViewShop',
    ViewOrdersReturn = 'ViewOrdersReturn',
    ViewShopItems = 'ViewShopItems',
    ViewExpenseReport = 'ViewExpenseReport',
    ViewCatalogueHidebutton = 'ViewCatalogueHidebutton',
    ViewCatalogueFilter = 'ViewCatalogueFilter',
    ViewCatalogueSalesbarchart = 'ViewCatalogueSalesbarchart',
    ViewTopSoldItems = 'ViewTopSoldItems',
    ViewEditButton = 'ViewEditButton',
    ViewNotification = 'ViewNotification',
}
