// expenseReport.downloads.ts
//
// PDF / Excel export engine for the Expense report. Extracted verbatim (same
// calculations/formatting) from ExpenseReport.tsx, mirroring the sibling
// `PNLReportComponents/pnlReport.downloads.ts` and
// `TaxReportComponents/taxReportExport.utils.ts` modules.

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import XLSX from 'xlsx-js-style';

import type { Expense } from '@/features/expenses';
import { resolveCompanyLogoBase64 } from '../../../Catalogue/hooks/useCompanyLogo';

/** Minimal local typing for the xlsx-js-style cell style shape (no upstream types shipped). */
interface XlsxFont { name?: string; sz?: number; bold?: boolean; italic?: boolean; color?: { rgb: string } }
interface XlsxFill { patternType: string; fgColor: { rgb: string } }
interface XlsxAlignment { horizontal?: string; vertical?: string; wrapText?: boolean }
interface XlsxBorderSide { style: string; color: { rgb: string } }
interface XlsxBorder {
  top?: XlsxBorderSide;
  bottom?: XlsxBorderSide;
  left?: XlsxBorderSide;
  right?: XlsxBorderSide;
}
interface XlsxCellStyle {
  font: XlsxFont;
  fill: XlsxFill | Record<string, never>;
  alignment: XlsxAlignment;
  border: XlsxBorder | Record<string, never>;
}
type XlsxCellValue = string | number | null;

export interface ExpenseSummary {
  total: number;
  count: number;
}

export interface ExpenseExportParams {
  filtered: Expense[];
  summary: ExpenseSummary;
  appliedFilters: { start: number; end: number };
  startDate: string;
  endDate: string;
  companyId: string | undefined;
}

/** `dd MMM yyyy` formatter matching the report's on-screen/export date style. */
export const formatExpenseDate = (ms: number) =>
  new Date(ms).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

/** Generates and downloads the expense report as a branded PDF. */
export async function downloadExpensePdf({
  filtered,
  summary,
  appliedFilters,
  startDate,
  endDate,
  companyId,
}: ExpenseExportParams): Promise<void> {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  doc.setFillColor(37, 99, 235); doc.rect(0, 0, pw, 6, 'F');
  doc.setFontSize(22); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 24, 39);
  doc.text('Expense Report', 14, 24);
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(107, 114, 128);
  doc.text(`Generated: ${formatExpenseDate(Date.now())}   |   Period: ${formatExpenseDate(appliedFilters.start)} to ${formatExpenseDate(appliedFilters.end)}`, 14, 31);
  // ===== GENERATION TAG (drawn first, reserves space for logo) =====
  const tagText = `Generated by SELLAR • ${new Date().toLocaleString('en-IN')}`;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);

  const textWidth = doc.getTextWidth(tagText);
  const paddingX = 2;
  const boxWidth = textWidth + paddingX * 2;
  const boxHeight = 5;

  const logoReservedWidth = 18; // space reserved for logo + gap, so tag never overlaps it
  const boxX = pw - 14 - logoReservedWidth - boxWidth;
  const boxY = 10;

  doc.setFillColor(245, 245, 245);
  doc.rect(boxX, boxY, boxWidth, boxHeight, 'F');

  doc.setTextColor(80, 80, 80);
  doc.text(tagText, boxX + paddingX, boxY + 3.5);

  doc.setTextColor(0, 0, 0);

  // ===== LOGO (drawn after, in its own reserved slot at top-right corner) =====
  try {
    const base64Logo = await resolveCompanyLogoBase64(companyId);
    if (base64Logo) {
      const img = new Image();
      img.src = base64Logo;
      await new Promise<void>((resolve) => {
        img.onload = () => {
          const logoWidth = 13;
          const logoHeight = (img.naturalHeight / img.naturalWidth) * logoWidth;
          const logoX = pw - logoWidth - 14;
          doc.addImage(base64Logo, 'PNG', logoX, 8, logoWidth, logoHeight);
          resolve();
        };
        img.onerror = () => resolve();
      });
    }
  } catch {
    // Continue without logo
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(17, 24, 39);

  autoTable(doc, {
    startY: 38,
    head: [['DATE', 'TITLE', 'DESCRIPTION', 'AMOUNT(Rs)']],
    body: filtered.map((e) => [formatExpenseDate(e.date), e.title, e.description, e.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })]),
    foot: [['TOTAL', '', '', summary.total.toLocaleString('en-IN', { minimumFractionDigits: 2 })]],
    theme: 'plain',
    styles: { font: 'helvetica', cellPadding: 7, fontSize: 10, textColor: [55, 65, 81] },
    headStyles: { fillColor: [249, 250, 251], textColor: [17, 24, 39], fontStyle: 'bold', lineWidth: { top: 1, bottom: 1 }, lineColor: [229, 231, 235] },
    footStyles: { fillColor: [255, 255, 255], textColor: [17, 24, 39], fontStyle: 'bold', lineWidth: { top: 1, bottom: 2 }, lineColor: [17, 24, 39] },
    alternateRowStyles: { fillColor: [252, 252, 252] },
    columnStyles: { 0: { cellWidth: 35 }, 1: { cellWidth: 30 }, 2: { cellWidth: 'auto' }, 3: { halign: 'right', cellWidth: 42 } },
    didDrawPage: () => {
      doc.setFontSize(9); doc.setTextColor(156, 163, 175);
      doc.text(`Page ${doc.getNumberOfPages()}`, pw - 14, ph - 10, { align: 'right' });
    },
  });
  doc.save(`Expense_Report_${startDate}_to_${endDate}.pdf`);
}

/** Generates and downloads the expense report as a styled Excel workbook. */
export function downloadExpenseExcel({
  filtered,
  summary,
  appliedFilters,
  startDate,
  endDate,
}: ExpenseExportParams): void {
  const s = (font: XlsxFont, fill?: XlsxFill, alignment?: XlsxAlignment, border?: XlsxBorder): XlsxCellStyle => ({
    font: { name: 'Arial', ...font }, fill: fill ?? {},
    alignment: alignment ?? { horizontal: 'center', vertical: 'center', wrapText: true }, border: border ?? {},
  });
  const solidFill = (rgb: string) => ({ patternType: 'solid', fgColor: { rgb } });
  const allBorders = { top: { style: 'thin', color: { rgb: 'CBD5E1' } }, bottom: { style: 'thin', color: { rgb: 'CBD5E1' } }, left: { style: 'thin', color: { rgb: 'CBD5E1' } }, right: { style: 'thin', color: { rgb: 'CBD5E1' } } };
  const bblr = { bottom: { style: 'thin', color: { rgb: 'CBD5E1' } }, left: { style: 'thin', color: { rgb: 'CBD5E1' } }, right: { style: 'thin', color: { rgb: 'CBD5E1' } } };

  const COLS = [{ header: '#', width: 6 }, { header: 'Date', width: 16 }, { header: 'Title', width: 20 }, { header: 'Description', width: 32 }, { header: 'Amount (₹)', width: 18 }];
  const colCount = COLS.length;
  const dataStartRow = 7;
  const totalRows = dataStartRow + filtered.length + 1;
  const aoa: XlsxCellValue[][] = Array.from({ length: totalRows }, () => Array(colCount).fill(null));

  aoa[0][0] = 'Expense Report';
  aoa[1][0] = `Generated: ${formatExpenseDate(Date.now())}   |   Period: ${formatExpenseDate(appliedFilters.start)} → ${formatExpenseDate(appliedFilters.end)}`;
  aoa[3][0] = 'SUMMARY';
  aoa[4][0] = `Total Expenses: ₹${summary.total.toLocaleString('en-IN', { minimumFractionDigits: 2 })}   |   Entries: ${summary.count}`;
  COLS.forEach((c, i) => { aoa[6][i] = c.header; });
  filtered.forEach((exp, idx) => {
    const r = dataStartRow + idx;
    aoa[r] = [idx + 1, formatExpenseDate(exp.date), exp.title, exp.description, exp.amount];
  });
  const footerRow = dataStartRow + filtered.length;
  aoa[footerRow] = ['TOTAL', '', '', '', summary.total];

  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws['!cols'] = COLS.map((c) => ({ wch: c.width }));
  ws['!rows'] = [{ hpt: 36 }, { hpt: 20 }, { hpt: 8 }, { hpt: 18 }, { hpt: 22 }, { hpt: 8 }, { hpt: 28 }, ...filtered.map(() => ({ hpt: 20 })), { hpt: 24 }];
  ws['!merges'] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: colCount - 1 } }, { s: { r: 1, c: 0 }, e: { r: 1, c: colCount - 1 } }, { s: { r: 3, c: 0 }, e: { r: 3, c: colCount - 1 } }, { s: { r: 4, c: 0 }, e: { r: 4, c: colCount - 1 } }];

  const styleCell = (addr: string, st: XlsxCellStyle) => { if (!ws[addr]) ws[addr] = { t: 's', v: '' }; ws[addr].s = st; };
  styleCell('A1', s({ sz: 16, bold: true, color: { rgb: 'FFFFFF' } }, solidFill('2563EB'), { horizontal: 'center', vertical: 'center' }));
  styleCell('A2', s({ sz: 9, italic: true, color: { rgb: '475569' } }, solidFill('DBEAFE'), { horizontal: 'center', vertical: 'center' }));
  styleCell('A4', s({ sz: 10, bold: true, color: { rgb: '1D4ED8' } }, solidFill('EFF6FF'), { horizontal: 'left', vertical: 'center' }, allBorders));
  styleCell('A5', s({ sz: 10, bold: true, color: { rgb: '166534' } }, solidFill('DCFCE7'), { horizontal: 'center', vertical: 'center' }, bblr));
  COLS.forEach((_, i) => {
    const addr = XLSX.utils.encode_cell({ r: 6, c: i });
    styleCell(addr, s({ sz: 10, bold: true, color: { rgb: 'FFFFFF' } }, solidFill('1E40AF'), { horizontal: i <= 3 ? 'left' : 'center', vertical: 'center' }, allBorders));
  });
  filtered.forEach((_, idx) => {
    const r = dataStartRow + idx;
    const isAlt = idx % 2 === 1;
    for (let ci = 0; ci < colCount; ci++) {
      const addr = XLSX.utils.encode_cell({ r, c: ci });
      styleCell(addr, s({ sz: 9, color: { rgb: '1E293B' } }, solidFill(isAlt ? 'F8FAFC' : 'FFFFFF'), { horizontal: ci === 4 ? 'center' : 'left', vertical: 'center' }, bblr));
      if (ci === 4 && ws[addr]) { ws[addr].t = 'n'; ws[addr].z = '₹#,##0.00'; }
    }
  });
  for (let ci = 0; ci < colCount; ci++) {
    const addr = XLSX.utils.encode_cell({ r: footerRow, c: ci });
    styleCell(addr, s({ sz: 10, bold: true, color: { rgb: '1E293B' } }, solidFill('E2E8F0'), { horizontal: ci <= 3 ? 'left' : 'center', vertical: 'center' }, { top: { style: 'medium', color: { rgb: '1E293B' } }, bottom: { style: 'medium', color: { rgb: '1E293B' } }, left: { style: 'thin', color: { rgb: 'CBD5E1' } }, right: { style: 'thin', color: { rgb: 'CBD5E1' } } }));
    if (ci === 4 && ws[addr]) { ws[addr].t = 'n'; ws[addr].z = '₹#,##0.00'; }
  }

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Expense Report');
  XLSX.writeFile(wb, `Expense_Report_${startDate}_to_${endDate}.xlsx`);
}
