import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Item } from '../../../constants/models';

// --- 3-TIER PRICING LOGIC HELPER ---
export const getEffectivePriceInfo = (item: Item) => {
  const mrp = Number(item.mrp || 0);
  const itemSalesPrice = Number(item.salesPrice || 0);
  const presetDiscount = Number(item.discount || 0);

  let salePrice = 0;
  let calculatedDiscount = 0;

  if (mrp > 0 && itemSalesPrice > 0) {
    // Case 1: Both exist. Ignore DB discount. Calculate diff.
    salePrice = itemSalesPrice;
    calculatedDiscount = ((mrp - itemSalesPrice) / mrp) * 100;
  } else if (itemSalesPrice > 0) {
    // Case 2: Only Sales Price exists. Apply DB discount.
    calculatedDiscount = presetDiscount;
    salePrice = itemSalesPrice * (1 - presetDiscount / 100);
  } else if (mrp > 0) {
    // Case 3: Only MRP exists. Apply DB discount.
    calculatedDiscount = presetDiscount;
    salePrice = mrp * (1 - presetDiscount / 100);
  }

  // Round to 2 decimal places to ensure clean UI numbers
  salePrice = Math.round((salePrice + Number.EPSILON) * 100) / 100;

  return {
    mrp,
    salePrice,
    discountPercent: Math.round(calculatedDiscount),
    hasDiscount: calculatedDiscount > 0,
    hasBothPrices: mrp > 0 && salePrice > 0 && salePrice < mrp,
  };
};

// 1. Converts ANY image format (WebP, AVIF, PNG) into a jsPDF-safe JPEG
const blobToNormalizedBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const url = URL.createObjectURL(blob);
    const img = new Image();
    img.crossOrigin = 'Anonymous';

    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');

      if (ctx) {
        ctx.fillStyle = '#FFFFFF';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL('image/jpeg', 0.8)); // 0.8 compression keeps PDF file size down
      } else {
        reject(new Error('Canvas context failed'));
      }
      URL.revokeObjectURL(url);
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Image load error'));
    };
    img.src = url;
  });
};

// 2. Fetches an item image and routes the blob through the Canvas normalizer above
const convertImageUrlToBase64 = async (url: string, itemName: string): Promise<string> => {
  if (!url) {
    console.warn(`⚠️ [${itemName}] No Image URL provided in the database.`);
    return '';
  }

  try {
    const cacheBuster = url + (url.includes('?') ? '&' : '?') + 'cb=' + new Date().getTime();
    const response = await fetch(cacheBuster, { mode: 'cors' });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const blob = await response.blob();

    // Pass through the normalizer
    return await blobToNormalizedBase64(blob);
  } catch {
    console.warn(`⚠️ [${itemName}] Direct fetch blocked. Trying Proxy...`);
    try {
      const proxyUrl = `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`;
      const proxyResponse = await fetch(proxyUrl);
      if (!proxyResponse.ok) throw new Error(`Proxy HTTP ${proxyResponse.status}`);
      const blob = await proxyResponse.blob();

      // Pass through the normalizer
      return await blobToNormalizedBase64(blob);
    } catch {
      console.error(`❌ [${itemName}] Both direct and proxy fetch failed.`);
      return '';
    }
  }
};

/**
 * Builds and downloads the PDF product catalogue for the given (already-filtered,
 * live-only) items. Mirrors the original inline `handleDownloadPDF` logic exactly;
 * throws on failure so the caller can alert + reset its own loading state.
 */
export async function downloadCataloguePdf(
  liveItemsToPrint: Item[],
  companyName: string,
  categoryName: string,
): Promise<void> {
  const doc = new jsPDF();

  // --- Document Header ---
  doc.setFontSize(18);
  doc.text(`${companyName} - ${categoryName}`, 14, 20);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by SELLAR.IN: ${new Date().toLocaleDateString()}`, 14, 26);

  const tableBody: (string | number)[][] = [];
  const tableImages: string[] = [];

  // --- Prepare Data (throttled to avoid rate limits) ---
  for (const item of liveItemsToPrint) {
    const { salePrice, mrp, hasBothPrices } = getEffectivePriceInfo(item);
    let base64Img = '';

    if (item.imageUrl) {
      // Fetch sequentially using the Canvas normalizer
      base64Img = await convertImageUrlToBase64(item.imageUrl, item.name || 'Unknown Product');

      // Tiny delay to prevent Google Cloud rate limits (429 errors)
      await new Promise((resolve) => setTimeout(resolve, 50));
    }

    const mrpText = hasBothPrices ? `Rs. ${mrp}` : '-';
    const salePriceText = `Rs. ${salePrice}`;

    tableBody.push([
      '', // Leaves the cell blank for the image
      item.name?.toUpperCase() || 'UNNAMED PRODUCT',
      mrpText,
      salePriceText,
    ]);

    tableImages.push(base64Img);
  }

  // --- Generate AutoTable ---
  autoTable(doc, {
    startY: 32,
    margin: { bottom: 25 }, // CRITICAL: Prevents table from drawing over the footer
    head: [['Image', 'Product Details', 'MRP', 'Sale Price']],
    body: tableBody,
    headStyles: { fillColor: [249, 115, 22], halign: 'center' }, // #F97316
    bodyStyles: { minCellHeight: 25, valign: 'middle' },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 'auto', fontStyle: 'bold', halign: 'center', textColor: [26, 59, 93] },
      2: { cellWidth: 25, halign: 'center', textColor: [156, 163, 175] },
      3: { cellWidth: 35, halign: 'center', fontStyle: 'bold', textColor: [249, 115, 22] },
    },
    didDrawCell: (data) => {
      // Manually draw the image inside the first column's cell
      if (data.column.index === 0 && data.cell.section === 'body') {
        const base64Img = tableImages[data.row.index];
        if (base64Img) {
          doc.addImage(base64Img, 'JPEG', data.cell.x + 2, data.cell.y + 2, 21, 21);
        }
      }
    },
    didDrawPage: () => {
      // --- Footer Branding Injection ---
      const pageSize = doc.internal.pageSize;
      const pageWidth = pageSize.width ? pageSize.width : pageSize.getWidth();
      const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
      const footerY = pageHeight - 12; // Base Y position near the bottom

      doc.setFontSize(10);

      // -- Line 1: Powered by SELLAR.IN --
      doc.setFont('helvetica', 'bold');
      const text1a = 'Powered by ';
      const text1b = 'SELLAR.IN';
      const w1a = doc.getTextWidth(text1a);
      const w1b = doc.getTextWidth(text1b);
      const startX1 = (pageWidth - (w1a + w1b)) / 2; // Centers the combined text

      doc.setTextColor(0, 0, 0); // Black
      doc.text(text1a, startX1, footerY - 5);

      doc.setTextColor(37, 99, 235); // Blue
      doc.text(text1b, startX1 + w1a, footerY - 5);

      // Draw underline for SELLAR.IN
      doc.setLineWidth(0.3);
      doc.setDrawColor(37, 99, 235);
      doc.line(startX1 + w1a, footerY - 4, startX1 + w1a + w1b, footerY - 4);

      // -- Line 2: Made with Love in India --
      doc.setFont('helvetica', 'normal');
      const text2a = 'Made with ';
      const text2b = 'Love';
      const text2c = ' in India';
      const w2a = doc.getTextWidth(text2a);
      const w2b = doc.getTextWidth(text2b);
      const w2c = doc.getTextWidth(text2c);
      const startX2 = (pageWidth - (w2a + w2b + w2c)) / 2;

      doc.setTextColor(0, 0, 128); // Dark Navy/Blackish for start
      doc.text(text2a, startX2, footerY);

      doc.setTextColor(239, 68, 68); // Red
      doc.text(text2b, startX2 + w2a, footerY);

      doc.setTextColor(0, 0, 128); // Dark Navy for end
      doc.text(text2c, startX2 + w2a + w2b, footerY);
    },
  });

  // --- Save the PDF ---
  const safeCompanyName = (companyName || 'Company').replace(/\s+/g, '_');
  const safeCategoryName = categoryName === 'All Products' ? 'Full_Catalogue' : categoryName.replace(/\s+/g, '_');

  doc.save(`${safeCompanyName}_${safeCategoryName}.pdf`);
}
